<a href="https://colab.research.google.com/github/Thitichaya2000/DWDM21/blob/main/Project_%E0%B8%81%E0%B8%A5%E0%B8%B8%E0%B9%88%E0%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#แหล่งที่มาชุดข้อมูล
*  สถิติหน่วยจำหน่าย แยกประเภทผู้ใช้ไฟฟ้า https://data.go.th/dataset/mea-data5
*  สถิติจำนวนผู้ใช้ไฟฟ้า แยกตามประเภทผู้ใช้ไฟฟ้า มค2562- เมย2564 https://data.go.th/dataset/mea-customer
*   สถิติหน่วยจำหน่ายแยกตามเขต https://data.go.th/dataset/mea3_per-district

In [1]:
import pandas as pd

In [2]:
from google.colab import drive #เชื่อม google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os # จัดการไฟล์และpath

In [35]:
#ข้อมูลชุดที่ 1
path = '/content/drive/My Drive/PROJECT_DWDM'
data_1 = pd.read_csv(os.path.join(path,'Dataone.csv'))
data_1

      ปี  เดือน  ... ไฟสาธารณะ   หน่วยขายรวมไฟสาธารณะ
0   2562   ม.ค.  ...      42.15              4,119.31
1   2562   ก.พ.  ...      38.15              4,188.50
2   2562  มี.ค.  ...      42.29              4,660.94
3   2562  เม.ย.  ...      40.96              4,709.44
4   2562   พ.ค.  ...      42.37              4,976.37
5   2562  มิ.ย.  ...      41.02              4,638.70
6   2562   ก.ค.  ...      42.41              4,524.05
7   2562   ส.ค.  ...      42.44              4,524.33
8   2562   ก.ย.  ...      41.12              4,309.26
9   2562   ต.ค.  ...      42.53              4,489.65
10  2562   พ.ย.  ...      41.31              4,281.11
11  2562   ธ.ค.  ...      42.71              3,882.71
12  2563   ม.ค.  ...      42.73              4,330.05
13  2563   ก.พ.  ...      39.99              4,202.37
14  2563  มี.ค.  ...      42.93              4,512.98
15  2563  เม.ย.  ...      41.66              4,119.77
16  2563   พ.ค.  ...      43.08              4,461.01
17  2563  มิ.ย.  ...      41.72              4,263.37
18  2563   ก.ค.  ...      43.14              4,318.83
19  2563   ส.ค.  ...      43.18              4,331.42
20  2563   ก.ย.  ...      41.82              4,321.11
21  2563   ต.ค.  ...      43.22              4,006.48
22  2563   พ.ย.  ...      41.86              3,963.26
23  2563   ธ.ค.  ...      43.27              3,831.19
24  2564   ม.ค.  ...      43.28              3,568.79
25  2564   ก.พ.  ...      39.10              3,780.66
26  2564  มี.ค.  ...      43.29              4,460.09
27  2564  เม.ย.  ...      41.90              4,243.76

[28 rows x 13 columns]

In [59]:
#ข้อมูลชุดที่ 2
data_2 = pd.read_csv(os.path.join(path,'Datatwo.csv'))
data_2

      ปี  ... จำนวนผู้ใช้ไฟฟ้า(ราย)
0   2562  ...            3,815,937
1   2562  ...            3,826,698
2   2562  ...            3,836,722
3   2562  ...            3,844,235
4   2562  ...            3,851,245
5   2562  ...            3,860,675
6   2562  ...            3,867,607
7   2562  ...            3,878,510
8   2562  ...            3,887,082
9   2562  ...            3,896,516
10  2562  ...            3,907,748
11  2562  ...            3,915,613
12  2563  ...            3,925,216
13  2563  ...            3,932,418
14  2563  ...            3,942,995
15  2563  ...            3,958,402
16  2563  ...            3,971,783
17  2563  ...            3,984,419
18  2563  ...            3,996,799
19  2563  ...            4,010,646
20  2563  ...            4,023,596
21  2563  ...            4,033,770
22  2563  ...            4,043,483
23  2563  ...            4,052,963
24  2564  ...            4,057,291
25  2564  ...            4,061,314
26  2564  ...            4,064,534
27  2564  ...            4,068,484

[28 rows x 11 columns]

In [39]:
#ข้อมูลชุดที่ 3
data_3 = pd.read_csv(os.path.join(path,'Datathree.csv'))
data_3

      ปี      เดือน  วัดเลียบ   ...  ลาดกระบัง   นวลจันทร์   ผู้ใช้ไฟฟ้าทั้งหมด
0   2562      ม.ค.     75,620   ...    156,172     182,331            3,815,937
1   2562      ก.พ.     75,577   ...    156,521     182,436            3,826,698
2   2562     มี.ค.     75,736   ...    157,307     182,636            3,836,722
3   2562     เม.ย.     75,756   ...    158,075     182,853            3,844,235
4   2562      พ.ค.     75,613   ...    158,443     182,836            3,851,245
5   2562     มิ.ย.     75,573   ...    158,880     183,108            3,860,675
6   2562      ก.ค.     75,688   ...    159,023     183,453            3,867,607
7   2562      ส.ค.     75,696   ...    159,492     184,261            3,878,510
8   2562      ก.ย.     75,738   ...    159,767     184,801            3,887,082
9   2562      ต.ค.     75,786   ...    160,002     185,430            3,896,516
10  2562      พ.ย.     76,035   ...    160,388     185,698            3,907,748
11  2562      ธ.ค.     76,024   ...    160,550     186,478            3,915,613
12  2563      ม.ค.     76,026   ...    160,947     186,523            3,925,216
13  2563      ก.พ.     75,977   ...    161,243     186,462            3,932,418
14  2563     มี.ค.     75,924   ...    161,577     186,689            3,942,995
15  2563     เม.ย.     75,968   ...    162,090     187,146            3,958,402
16  2563      พ.ค.     76,080   ...    162,543     187,550            3,971,783
17  2563     มิ.ย.     76,076   ...    162,927     187,885            3,984,419
18  2563      ก.ค.     76,115   ...    163,361     188,109            3,996,799
19  2563      ส.ค.     76,018   ...    163,674     188,328            4,010,646
20  2563      ก.ย.     76,051   ...    164,007     188,719            4,023,596
21  2563      ต.ค.     76,068   ...    164,358     188,925            4,033,770
22  2563      พ.ย.     76,071   ...    164,596     189,598            4,043,483
23  2563      ธ.ค.     76,205   ...    164,912     190,575            4,052,963
24  2564      ม.ค.     75,957   ...    165,164     190,719            4,057,291
25  2564      ก.พ.     75,897   ...    165,454     190,792            4,061,314
26  2564    มี.ค.      75,884   ...    165,815     190,911            4,064,534
27  2564    เม.ย.      76,165   ...    166,024     190,932            4,068,484

[28 rows x 21 columns]

##เช็ค Missing

In [41]:
data_1.isnull().any()

ปี                                         False
เดือน                                      False
บ้านอยู่อาศัย                              False
กิจการขนาดเล็ก                             False
กิจการขนาดกลาง                             False
กิจการขนาดใหญ่                             False
กิจการเฉพาะอย่าง                           False
องค์กรที่ไม่แสวงหากำไร                     False
ไฟฟ้าชั่วคราว                              False
สถานีอัดประจุไฟฟ้า สำหรับยานยนต์ไฟฟ้า *    False
หน่วยขายไม่รวมไฟสาธารณะ                    False
ไฟสาธารณะ                                  False
หน่วยขายรวมไฟสาธารณะ                       False
dtype: bool

In [46]:
data_2.isnull().any()

กิจการขนาดใหญ่(ราย)                             False
กิจการเฉพาะอย่าง(ราย)                           False
องค์กรที่ไม่แสวงหากำไร(ราย)                     False
ผู้ใช้ไฟฟ้าชั่วคราว(ราย)                        False
สถานีอัดประจุไฟฟ้า สำหรับยานยนต์ไฟฟ้า *(ราย)    False
จำนวนผู้ใช้ไฟฟ้า(ราย)                           False
dtype: bool

In [44]:
data_3.isnull().any()

ปี                      False
เดือน                   False
 วัดเลียบ               False
 คลองเตย                False
 ยานนาวา                False
 บางกะปิ                False
 มีนบุรี                False
 สมุทรปราการ            False
 บางพลี                 False
 สามเสน                 False
 นนทบุรี                False
 บางใหญ่                False
 ธนบุรี                 False
 ราษฎร์บูรณะ            False
 บางขุนเทียน            False
 บางเขน                 False
 บางนา                  False
 บางบัวทอง              False
 ลาดกระบัง              False
 นวลจันทร์              False
 ผู้ใช้ไฟฟ้าทั้งหมด     False
dtype: bool

#รวม 2 ตารางเข้าด้วยกัน

In [63]:
merged_table_new2 = data_1.merge(data_2,how='left',left_on='ปี',right_on='ปี') 
merged_table_new2

       ปี  ... จำนวนผู้ใช้ไฟฟ้า(ราย)
0    2562  ...            3,815,937
1    2562  ...            3,826,698
2    2562  ...            3,836,722
3    2562  ...            3,844,235
4    2562  ...            3,851,245
..    ...  ...                   ...
299  2564  ...            4,068,484
300  2564  ...            4,057,291
301  2564  ...            4,061,314
302  2564  ...            4,064,534
303  2564  ...            4,068,484

[304 rows x 23 columns]

#รวม 3 ตารางเข้าด้วยกัน

In [67]:
merged_table_new3 = merged_table_new2.merge(data_3,how='left',left_on='ปี',right_on='ปี') 
merged_table_new3

        ปี เดือน_x บ้านอยู่อาศัย  ...   ลาดกระบัง    นวลจันทร์   ผู้ใช้ไฟฟ้าทั้งหมด
0     2562    ม.ค.      1,035.21  ...     156,172      182,331            3,815,937
1     2562    ม.ค.      1,035.21  ...     156,521      182,436            3,826,698
2     2562    ม.ค.      1,035.21  ...     157,307      182,636            3,836,722
3     2562    ม.ค.      1,035.21  ...     158,075      182,853            3,844,235
4     2562    ม.ค.      1,035.21  ...     158,443      182,836            3,851,245
...    ...     ...           ...  ...          ...          ...                  ...
3515  2564   เม.ย.      1,423.99  ...     166,024      190,932            4,068,484
3516  2564   เม.ย.      1,423.99  ...     165,164      190,719            4,057,291
3517  2564   เม.ย.      1,423.99  ...     165,454      190,792            4,061,314
3518  2564   เม.ย.      1,423.99  ...     165,815      190,911            4,064,534
3519  2564   เม.ย.      1,423.99  ...     166,024      190,932            4,068,484

[3520 rows x 43 columns]

In [68]:
merged_table_new3.isnull().any()

ปี                                              False
เดือน_x                                         False
บ้านอยู่อาศัย                                   False
กิจการขนาดเล็ก                                  False
กิจการขนาดกลาง                                  False
กิจการขนาดใหญ่                                  False
กิจการเฉพาะอย่าง                                False
องค์กรที่ไม่แสวงหากำไร                          False
ไฟฟ้าชั่วคราว                                   False
สถานีอัดประจุไฟฟ้า สำหรับยานยนต์ไฟฟ้า *         False
หน่วยขายไม่รวมไฟสาธารณะ                         False
ไฟสาธารณะ                                       False
หน่วยขายรวมไฟสาธารณะ                            False
เดือน_y                                         False
บ้านอยู่อาศัย(ราย)                              False
กิจการขนาดเล็ก(ราย)                             False
กิจการขนาดกลาง(ราย)                             False
กิจการขนาดใหญ่(ราย)                             False
กิจการเฉพาะอย่าง(ราย)                           False
องค์กรที่ไม่แสวงหากำไร(ราย)                     False
ผู้ใช้ไฟฟ้าชั่วคราว(ราย)                        False
สถานีอัดประจุไฟฟ้า สำหรับยานยนต์ไฟฟ้า *(ราย)    False
จำนวนผู้ใช้ไฟฟ้า(ราย)                           False
เดือน                                           False
 วัดเลียบ                                       False
 คลองเตย                                        False
 ยานนาวา                                        False
 บางกะปิ                                        False
 มีนบุรี                                        False
 สมุทรปราการ                                    False
 บางพลี                                         False
 สามเสน                                         False
 นนทบุรี                                        False
 บางใหญ่                                        False
 ธนบุรี                                         False
 ราษฎร์บูรณะ                                    False
 บางขุนเทียน                                    False
 บางเขน                                         False
 บางนา                                          False
 บางบัวทอง                                      False
 ลาดกระบัง                                      False
 นวลจันทร์                                      False
 ผู้ใช้ไฟฟ้าทั้งหมด                             False
dtype: bool